// SPDX-FileCopyrightText: 2026 ScriptKittyOS and the Kotiko contributors
// SPDX-License-Identifier: Apache-2.0

// Generated by spec/tools/sync-extension.mjs from spec/rules.json. Do not edit: change
// spec/ and run `node spec/tools/sync-extension.mjs`. The content scripts' rules.
(() => {
  const RULES = {"max_page_concepts":500,"max_page_langs_per_concept":3};
  if (typeof module !== "undefined" && module.exports) module.exports = RULES;
  else globalThis.KOTIKO_PAGE_RULES = RULES;
})();
